language: ruby
before_install: gem install bundler
script: "bundle exec rspec spec"
services: mongodb
env:
  - COVERAGE=true
rvm:
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - jruby-head
  - rbx-19mode
  - ruby-head
matrix:
  allow_failures:
    - rvm:
      - jruby-19mode
      - jruby-head
      - ruby-head
      - rbx-19mode
